### PR TITLE
Add fuse

### PR DESCRIPTION
**Pull request by ashuntu**
Fixes the initial error with Fuse/Appimage games. Games still have mount permissions errors

### CODE REVIEW

**Comment by ZoopOTheGoop** [comment]
@ashuntu any reason this is still a draft?

**Comment by ZoopOTheGoop** [comment]
yeah just figured that out sorry lol

**Comment by ZoopOTheGoop** [comment]
@ashuntu try my new fix, works for me

**Comment by ashuntu** [comment]
It does work, but like you said not ideal. I think this is fine considering the rarity of appimage.

**Review by ZoopOTheGoop — APPROVED** [review]

**Comment by ZoopOTheGoop** [comment]
merge whenever, we can change it if the snapd people have a better idea

**Pull request merged**
