### PR TITLE
Add script to check for 32-bit NVIDIA libraries

### PR DESCRIPTION
**Pull request by ashuntu**
Adds a script that runs right before Steam that checks for the presence of 32-bit NVIDIA libraries (assuming NVIDIA modules are found and 64-bit libraries are also present). If 32-bit libraries aren't found, a dialog is presented suggesting installing them.

This uses `modinfo` on NVIDIA kernel modules and checks for library paths in `/var/lib/snapd/hostfs`.

Currently looks something like this: 

You can run the script from inside the shell and pass the `--show` flag to force the dialog to show even if you meet the NVIDIA requirements, and `--reset` to show the dialog if you had previously selected "Do not show again"

### CODE REVIEW

**Comment by kenvandine** [comment]
Can you try to make that text in the dialog selectable so users can just copy and paste the command?  And it would also be nice to make the link clickable.

**Comment by ashuntu** [comment]
`--selectable-labels` has a side effect of the text starting selected, I'm not sure if there is a fix for that

**Comment by kenvandine** [comment]
In testing the latest changes (without the 32 driver installed) I'm getting this error:

Traceback (most recent call last):
  File "/snap/steam/x3/bin/nvidia32", line 81, in <module>
    if nvidia_missing():
  File "/snap/steam/x3/bin/nvidia32", line 42, in nvidia_missing
    version = nvidia_version()
  File "/snap/steam/x3/bin/nvidia32", line 22, in nvidia_version
    nvidia_version = os.popen(
IndexError: list index out of range

**Comment by ashuntu** [comment]
> In testing the latest changes (without the 32 driver installed) I'm getting this error:

What's your output of `modinfo /usr/lib/modules/$(uname -r)/kernel/nvidia*/nvidia.ko | grep "version"` from the Steam shell?

**Comment by kenvandine** [comment]
> > In testing the latest changes (without the 32 driver installed) I'm getting this error:
> 
> What's your output of `modinfo /usr/lib/modules/$(uname -r)/kernel/nvidia*/nvidia.ko | grep "version"` from the Steam shell?

modinfo: ERROR: Module /usr/lib/modules/6.2.0-27-generic/kernel/nvidia*/nvidia.ko not found.


My nvidia.ko is in:
/usr/lib/modules/6.2.0-27-generic/updates/dkms/

**Comment by kenvandine** [comment]
This works better, but I think it would be better to make this a blocking dialog so we don't risk it losing focus.  I think to do that, it'll need a shell script wrapper that we add to the command-chain after desktop-launch.

**Comment by ashuntu** [comment]
I can set the window to always stay on top, how about that?

Steam can take a while to start, I feel like blocking it entirely wouldn't be the best user experience. Plus, it allows updates and other Steam things to process in the background while the user considers the dialog.

**Comment by kenvandine** [comment]
@ashuntu the copy action is copying the template, not what's actually displayed.  For example this is what i got in the paste buffer even thought the rendered text was correct:

```
sudo dpkg --add-architecture i386
sudo apt update
sudo apt install libnvidia-gl-{}:i386
```

**Review by kenvandine — APPROVED** [review]
Thanks, that works better now

**Pull request merged**
